language: node_js
node_js: stable
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
  - export LC_CTYPE=ja_JP.UTF-8
  - GIT_COMMITTER_NAME=kubosho_
  - GIT_COMMITTER_EMAIL=ta2@o2p.jp
  - GIT_AUTHOR_NAME=kubosho_
  - GIT_AUTHOR_EMAIL=ta2@o2p.jp
before_install: openssl aes-256-cbc -K $encrypted_19d31b446274_key -iv $encrypted_19d31b446274_iv -in github_deploy_key.enc -out github_deploy_key -d
script: echo "no test specified"
after_success:
  - |
      $(npm bin)/set-up-ssh --key "$encrypted_19d31b446274_key" \
                            --iv "$encrypted_19d31b446274_iv" \
                            --path-encrypted-key ".travis/github_deploy_key.enc"

      $(npm bin)/update-branch --commands "npm run build" \
                               --commit-message "Update website [skip ci]" \
                               --directory "./public" \
                               --distribution-branch "gh-pages" \
                               --source-branch "master"
